AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example API for Contacts System

Parameters:
  PythonVersion:
    Default: python3.9
    Description: Python version for lambda functions
    Type: String

Resources:
  contactsdb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: contacts-db
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
